version: '3.8'

services:
  db_crudjava:
    container_name: db_crudjava
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: db_app
    ports:
      - "5431:5432"

  pgadmin_java:
    container_name: pgadmin_java
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmindata:
